#=================================================
#   Description: Build OpenWrt using GitHub Actions
#   Lisence: MIT
#   Author: P3TERX
#   Blog: https://p3terx.com
#=================================================

name: Build OpenWrt k2

on: 
  push:
    tags:
      - "k2_*"
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        ln -sf packages openwrt/package/diy-packages
        ln -sf files openwrt/files
        chmod +x diy.sh
        [ -e "k2.config" ] && cp k2.config openwrt/.config
        cd openwrt
        ../diy.sh
        make defconfig

    - name: Download package
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build
      run: |
        cd openwrt
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

#        - name : Upload artifact
#        uses: actions/upload-artifact@master
#        with:
#        name: ${{GITHUB_REF}}
#        path: openwrt/bin  vincentchen/release-action@v1

#    - name : Release
#      uses: fnkr/github-action-ghr@v1
#      env:
#        GHR_COMPRESS: gz
#        GHR_PATH: openwrt/bin
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Assemble artifact
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        find ./openwrt/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
        find ./openwrt/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
        
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt K2 firmware
        path: ./artifact/
